### ISSUE TITLE
Program crashes on movement input

### ISSUE THREAD

**Issue by sadmansk** [uwnrg/minotaur-cpp#21]

**Comment by wyxzou** [comment]
A quick update:

So there seems to be a couple of errors associated with this:

Giving it the user input "up" or "right" crashes the program immediately.

Giving it the user input "down" or "left" does not crash the program on the first iteration. However, it does so after a few.

![image](https://cloud.githubusercontent.com/assets/15041340/24840855/ae5ea496-1d43-11e7-9466-b91bfc490b38.png)

Even though I am not connected to anything, it still logs "Moved ... in ... milliseconds" instead of saying "The movement ... could not be completed".

(Nothing should be connected to the ports for these errors)

**Comment by wyxzou** [comment]
There might be some problems with the threading, but I still haven't figured out why "down" and "left" works the first time, and crashes after a few.

**Comment by sadmansk** [comment]
@wyxzou The problem was there before threading was integrated if i remember correctly. I opened and closed this issue (https://github.com/uwnrg/minotaur-cpp/issues/9) after we deprecated EMMA, but since SAM also uses a serial port, the issue resurfaced. And this was before multithreading was added. I suspect it has something to do with exception catching, since when I was trying to debug this issue on Visual Studio, the exception was reported and caught, and the IDE gave me the option to "Continue" which made the logger report the movement to the screen.

**Comment by wyxzou** [comment]
So I created a PR for this, and is something like that what you want? I couldn't seem to get the exact exception you were talking about on Qt. The exception I got was something like:

QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
libc++abi.dylib: terminating with uncaught exception of type std::exception_ptr

**Comment by Mogball** [comment]
throw "Action could not be completed"; will throw char const* which is caught by catch(...) after which throw std::current_exception(); is called. I added catch(char const *e) { //log err } to correctly handle the exception.

This doesn't occur when moving down(0, -1) or left(-1, 0) because these -1's are passed as 'value' to Actuator::moveActuator(..., const int value, ...) which then does

for (int i = value; i > 0; i--) { ... }

so no code is executed
